### PR TITLE
fix(signals): make it compatible to Django 4.X.

### PR DESCRIPTION
**Pull request by max-wittig**
This requires a major release

Fixes https://github.com/django-notifications/django-notifications/issues/322

/cc @nemesisdesign @PetrDlouhy

### CODE REVIEW

**Review by dmytrotrunykov — APPROVED** [review]

**Comment by max-wittig** [comment]
@AlvaroLQueiroz @nemesisdesign @LegoStormtroopr @yangyubo @zhang-z Would one of you mind to take a look? Or what's the state of `django-notifications`?

**Comment by PetrDlouhy** [comment]
@max-wittig It seems pretty straightforward. Did you consider putting the argument description to docstring as suggested at https://docs.djangoproject.com/en/4.0/releases/3.1/#id2?

**Comment by PetrDlouhy** [comment]
@max-wittig The example of docstring taken from `django-plans` is
```python
account_automatic_renewal = Signal()
account_automatic_renewal.__doc__ = """
Try to renew the account automatically.
Should renew the user's UserPlan by recurring payments. If this succeeds, the plan should be extended.

sends arguments: 'user'
"""
```

**Review by pandafy — CHANGES_REQUESTED** [review]
While testing locally, I am getting following warning:

```
WARNINGS:
notifications.Notification: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the Config.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'
```

I believe we need to following change to make django-notifications completely backward compatible: 

```diff
diff --git a/notifications/apps.py b/notifications/apps.py
index 2a1a387..bf3648a 100644
--- a/notifications/apps.py
+++ b/notifications/apps.py
@@ -5,6 +5,7 @@ from django.apps import AppConfig
 
 class Config(AppConfig):
     name = "notifications"
+    default_auto_field = 'django.db.models.BigAutoField'
 
     def ready(self):
         super(Config, self).ready()
```

**Review by nemesisdesign — APPROVED** [review]

**Comment by max-wittig** [comment]
Ahh sorry I didn't follow up here. But thanks for the merge and follow up!

**Pull request merged**
