### PR TITLE
indexing `deleted` and `unread` fields to increase performance

### PR DESCRIPTION
**Pull request by harrypotterismyname**

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
Do you have any evidence that this has increased performance. It seems obvious, but it would be good to see some metrics around this.

**Comment by suoinguon** [comment]
When you have millions of records in this table , usually there is more requests to query the unread notification than requests to write to the table . That what I have; a lot of queries take more than 30 seconds to respond in my DB . 

After trying to optimize it, actually there are 3 indexes we need: unread, deleted, and `recipient and unread` together . This is what I have for my fork 

https://github.com/suoinguon/django-notifications/blob/master/notifications/models.py

**Comment by yangyubo** [comment]
@suoinguon I'd like to merge this PR, but it lacks migration script to add the db index, could you please  write a migration script?

**Comment by gabrielpiccolo4** [comment]
Hey guys how is the status of this pull going? Performance is really important ;)

**Comment by psychok7** [comment]
@yangyubo @harrypotterismyname this as been sitting here for too long. if you don't mind i can take over and create the migrations so it's merged

**Comment by AlvaroLQueiroz** [comment]
@psychok7 We appreciate that!!

**Pull request closed without merging**
