### PR TITLE
Fix live updating notifications

### PR DESCRIPTION
**Pull request by LegoStormtroopr**
This fixes a number of broken issues, including #81 and #82.

Wait for a merge.

### CODE REVIEW

**Comment by thetylerhayes** [comment]
@yangyubo Been a few weeks, can we push this through? Live notifications in templates are effectively broken without this.

**Comment by LegoStormtroopr** [comment]
@thetylerhayes Can you pull this branch and do a short code review? I'll do a double check this weekend as well, but don't want to make the same mistakes again.

**Comment by thetylerhayes** [comment]
Yep will do

**Comment by yangyubo** [comment]
@thetylerhayes sorry for late, I will merge it after you have done code review.

**Comment by yangyubo** [comment]
@LegoStormtroopr @thetylerhayes , is it ready to merge this PR?

**Comment by LegoStormtroopr** [comment]
Ok, I have some free time this weekend, and a vested interest in progressing this. I will triple-check the code on a fresh test server, and commit if no other comments come through.

**Comment by LegoStormtroopr** [comment]
I've added a small test page for verifying the live-updater works. And it does now. Happy for this to be merged in.

**Comment by yangyubo** [comment]
👍 Nice job!

**Comment by thetylerhayes** [comment]
:+1: thanks for doing this. sorry, got busy with business stuff and wasn't able to dive in. we'll test this out too, though i'm sure it's great! thanks again

**Pull request merged**
