### PR TITLE
Avoid importing models in models

### PR DESCRIPTION
**Pull request by funkybob**
Use lazy relation resolution for ForeignKey fields
Use `django.db.models.get_model` or `django.apps.apps.get_model` to get ContentType model in model methods.

### CODE REVIEW

**Comment by zhang-z** [comment]
@funkybob , thank you for the contribution.

I know lazy relation resolution is needed to avoid circular model imports in some cases. But importing models also has a benefit that if you use IDE's (e.g. Pycharm) refactoring feature to rename a model, the direct importing works better. In our case, circular model imports doesn't exist because notification app imports Django's builtin app while the reversed import won't happen. So is there any general discussion on why lazy relation resolution is preferred over importing models?

**Comment by funkybob** [comment]
Personally, I always use lazy references, but I don't use PyCharm, so don't know its limitations.  However, I do agree a good discussion on the benefits is warranted, so have opened one on the django-developers mailing list.

I'm quite sure I was driven to that change to prevent app state not ready errors when migrating a project from 1.4 to 1.9... I will verify tomorrow.

**Comment by zhang-z** [comment]
@funkybob , thanks for opening the discussion. Let me pasted the link [here](https://groups.google.com/forum/#!topic/django-developers/5yoR9K4c41I).

**Comment by zhang-z** [comment]
@funkybob , from the mailing list discussion, seems no more benefits of string FK references have been revealed, other than solving circular relations when needed. On the other side, regular FK references may help IDE to detect typos and dependencies. Do you think we can close this pull request until find more findings to support string FK references?

**Pull request closed without merging**
