### PR TITLE
Add __str__ to Notification Model to support Python 3

### PR DESCRIPTION
**Pull request by philroche**
Added __str__ method to Notification Model to support Python 3

### CODE REVIEW

**Comment by yangyubo** [comment]
Hi @philroche , could you please elaborate what will happens without `__str__` method?
Thank you.

**Comment by philroche** [comment]
See http://stackoverflow.com/a/13357382/571106.

When listing notifications only "Notification object" is displayed.

**Comment by yangyubo** [comment]
@philroche great, thank you.

**Comment by philroche** [comment]
Awesome - thank you for the project. Very useful

**Pull request merged**
