### PR TITLE
remove dependency on jsonfield, use Django default JSONField

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by bsolomon1124** [comment]
Related: https://github.com/django-notifications/django-notifications/pull/160, https://github.com/django-notifications/django-notifications/issues/152

**Comment by hamstap85** [comment]
My understanding of the migrations system, this is the incorrect way to do it. You're changing history, and the structure of the defined field classes is entirely different, including the internal column type of the DB engine. This will cause problems for any existing project. The same applies to https://github.com/django-notifications/django-notifications/pull/160

**Comment by PetrDlouhy** [comment]
I was implementing this on an existing project, and I didn't experience any problems. But I didn't check whether the internal structure - I expected that it uses JSON db type in both cases. But you are right, the structure can differ somehow or it could work only in some cases (like on PostgreSQL database).

What do you suggest to do? I think we need to change the migration history somehow, if we want to truly drop the `jsonfield` dependency.

**Comment by hamstap85** [comment]
I don't yet know the best practices for doing this sort of thing, but I agree at some point the `jsonfield` dependency should be dropped since the database version matrix that Django's native `JSONField` supports aligns with versions that people should be using anyway for stability and support and such.

I feel it needs to go through a deprecation release at the very least so that anyone who uses this can make the shift themselves on one version with a setting toggle or something.

**Comment by hamstap85** [comment]
@PetrDlouhy @yangyubo I've looked into how this can be done and I've come up with three possible migrations https://github.com/django-notifications/django-notifications/pull/332 https://github.com/django-notifications/django-notifications/pull/333 https://github.com/django-notifications/django-notifications/pull/334

**Comment by AlvaroLQueiroz** [comment]
Fixed on [version 2](/django-notifications/django-notifications/tree/v2-alpha)

**Pull request closed without merging**
