### PR TITLE
Test python 3.8 and Django 3.0

### PR DESCRIPTION
**Pull request by hamstap85**
Aligns the doc specs to match tested versions

We're trying to upgrade to Django 3.0 as soon as possible, so I'm going through all our dependencies and helping ensure they work on the latest version of everything.

### CODE REVIEW

**Comment by hamstap85** [comment]
tox passes locally, possibly the django 1.11 version in the travis envs needs to be latest

**Comment by hamstap85** [comment]
@nemesisdesign That was mainstream support, LTS is still active until about April https://www.djangoproject.com/download/#supported-versions unless you don't feel the need to support it LTS

**Comment by hamstap85** [comment]
@nemesisdesign Is there a target date for the version support shift release?

**Comment by aaronn** [comment]
Would love to see this merged soon. @nemesisdesign I saw you mentioned you didn't have pypi access before– do you have it now? Or are you doing a fork?

**Comment by tdruez** [comment]
+1 on merging this, it's a blocker for upgrading to Django 3.0

**Comment by nemesisdesign** [comment]
Got access, let's move on!

**Comment by aaronn** [comment]
Exciting!

**Pull request merged**
